### ISSUE TITLE
error with codes and websites

### ISSUE THREAD

**Issue by cv-lab-x** [pengyuanli/PDFigCapX#3]
thanks for your great work, but i got some errors when run the codes and use the websites,

websites error `该网页无法正常运作www.eecis.udel.edu 未发送任何数据。
ERR_EMPTY_RESPONSE
`
codes error `msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FigCap.py", line 73, in <module>
    info['fig_no_est']=0
NameError: name 'info' is not defined`

Looking forward to your reply, thanks! @pengyuanli

**Comment by SohamTolwala** [comment]
great work but same error while running the FigCap.py:
Traceback (most recent call last):
  File "E:\BACKUP\PDF_FigCapX\PDFigCapX\code\FigCap.py", line 71, in <module>
    info['fig_no_est']=0
NameError: name 'info' is not defined
